//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUMUON
    {
        public int MaChiTietPhieuMuon { get; set; }
        public string MaSach { get; set; }
        public string MaPhieuMuon { get; set; }
        public System.DateTime NgayTra { get; set; }
        public int TienPhat { get; set; }
        public string TinhTrang { get; set; }
        public int SoLuong { get; set; }
    
        public virtual PHIEUMUON PHIEUMUON { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
