//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUMUON()
        {
            this.CHITIETPHIEUMUONs = new HashSet<CHITIETPHIEUMUON>();
        }
    
        public string MaPhieuMuon { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public Nullable<int> TongTienPhat { get; set; }
        public System.DateTime HanTra { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string TaiKhoanThuThu { get; set; }
        public string TaiKhoanDocGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUMUON> CHITIETPHIEUMUONs { get; set; }
        public virtual TAIKHOANDOCGIA TAIKHOANDOCGIA1 { get; set; }
        public virtual TAIKHOANTHUTHU TAIKHOANTHUTHU1 { get; set; }
    }
}
